name: first workflow

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 * * * *'  # Executa a cada hora (no minuto 0)
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      name: Check out repository code
      uses: actions/checkout@v4

      name: Rodar script
      uses: echo "Executar código"
